

@scheme = https
@ades = test.eodatahub.org.uk/ades
@username=sparkgeouser
@workspace = sparkgeouser

@executeStatus = {{executeProcess.response.headers.Location}}


@processName = lst-filter



###

# @name executeProcess
POST https://test.eodatahub.org.uk/ades/{{workspace}}/ogc-api/processes/{{processName}}/execution HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json
Prefer: respond-async

< workflow_input.json

###

# @name getExecuteStatus
GET {{executeStatus}} HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###


# @name getResults
GET https://{{username}}.workspaces.test.eodhp.eco-ke-staging.com/files/workspaces-eodhp-test/processing-results/cat_{{getExecuteStatus.response.body.jobID}}.json
Authorization: Bearer {{token}}
Accept: application/json

###


# @name getItem
GET https://sparkgeouser.workspaces.test.eodhp.eco-ke-staging.com/files/workspaces-eodhp-test/processing-results/cat_{{getExecuteStatus.response.body.jobID}}/col_{{getExecuteStatus.response.body.jobID}}/data-1729000851.8787746.json
Authorization: Bearer {{token}}
Accept: application/json
###
# @name getItemManual
GET https://sparkgeouser.workspaces.test.eodhp.eco-ke-staging.com/files/workspaces-eodhp-test/processing-results/cat_bfd833e2-8afd-11ef-8657-9625a5233070/col_bfd833e2-8afd-11ef-8657-9625a5233070/data-1729000851.8787746.json
Authorization: Bearer {{token}}
Accept: application/json

###

# @name getCsv
GET https://sparkgeouser.workspaces.test.eodhp.eco-ke-staging.com/files/workspaces-eodhp-test/processing-results/cat_{{getExecuteStatus.response.body.jobID}}/col_{{getExecuteStatus.response.body.jobID}}/data.csv
Authorization: Bearer {{token}}
Accept: application/json