

@scheme = https
@ades = test.eodatahub.org.uk/ades
@username=sparkgeouser
@workspace = sparkgeouser

@deployStatus = {{deployProcessJson.response.headers.Location}}
@executeStatus = {{executeProcess.response.headers.Location}}

@jobid = {{getExecuteStatus.response.body.jobID}}

@processName = lst-current




###

# @name listProcesses
GET {{scheme}}://{{ades}}/{{username}}/ogc-api/processes HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

# @name deleteProcess
DELETE {{scheme}}://{{ades}}/{{username}}/ogc-api/processes/{{processName}} HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###


# @name deployProcessJson
POST {{scheme}}://{{ades}}/{{username}}/ogc-api/processes HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/cwl+yaml

< ../get_asset_values.cwl

###

# @name getProcessDetails
GET {{scheme}}://{{ades}}/{{username}}/ogc-api/processes/{{processName}} HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json
